version: "3"
services:
    mssql1:
      build: ./mssql1
      volumes:
        - mydata:/var/opt/backups
        - sharedpath:/sharedpath
      environment:
          SA_PASSWORD: "Password1234!"
          ACCEPT_EULA: "Y"
          MSSQL_BACKUP_DIR: /var/opt/backups
          TZ: America/New_York
          MSSQL_AGENT_ENABLED: "True"
      ports:
        - "2500:1433"
      container_name: mssql1
      hostname: mssql1
    mssql2:
      build: ./mssql2
      volumes:
        - mydata:/var/opt/backups
        - sharedpath:/sharedpath
      environment:
          SA_PASSWORD: "Password1234!"
          ACCEPT_EULA: "Y"
          MSSQL_BACKUP_DIR: /var/opt/backups
          TZ: America/New_York
          MSSQL_AGENT_ENABLED: "True"
      ports:
        - "2600:1433"
      container_name: mssql2
      hostname: mssql2
    mssql3:
      build: ./mssql3
      volumes:
        - mydata:/var/opt/backups
        - sharedpath:/sharedpath
      environment:
          SA_PASSWORD: "Password1234!"
          ACCEPT_EULA: "Y"
          MSSQL_BACKUP_DIR: /var/opt/backups
          TZ: America/New_York
          MSSQL_AGENT_ENABLED: "True"
      ports:
        - "2700:1433"
      container_name: mssql3
      hostname: mssql3
volumes:
  mydata:
  sharedpath: